# Generated by Django 4.2.2 on 2023-06-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registereduser',
        ),
    ]
