# Generated by Django 4.2.2 on 2023-06-24 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bibilocheck', '0002_delete_registereduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statusupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('publisheddate', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.CharField(max_length=500, null=True)),
                ('startdate', models.DateField(null=True)),
                ('completedate', models.DateField(null=True)),
                ('note', models.TextField(max_length=500, null=True)),
                ('Bookid', models.CharField(max_length=255, null=True)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
