# Generated by Django 4.2.2 on 2023-06-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0005_alter_statusupload_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupload',
            name='description',
            field=models.TextField(max_length=1048576, null=True),
        ),
    ]
