# Generated by Django 4.2.2 on 2023-06-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0006_alter_statusupload_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupload',
            name='Bookid',
            field=models.CharField(max_length=1048576, null=True),
        ),
        migrations.AlterField(
            model_name='statusupload',
            name='publisheddate',
            field=models.CharField(max_length=1048576, null=True),
        ),
        migrations.AlterField(
            model_name='statusupload',
            name='status',
            field=models.CharField(max_length=1048576),
        ),
    ]
