# Generated by Django 4.2.2 on 2023-06-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0007_alter_statusupload_bookid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupload',
            name='Bookid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statusupload',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statusupload',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='statusupload',
            name='note',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='statusupload',
            name='publisheddate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statusupload',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='statusupload',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
