# Generated by Django 4.2.2 on 2023-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0008_alter_statusupload_bookid_alter_statusupload_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupload',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
