# Generated by Django 4.2.2 on 2023-06-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0009_alter_statusupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupload',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('reading', 'reading'), ('planning', 'planning'), ('dropped', 'dropped')], max_length=20),
        ),
    ]
