# Generated by Django 4.2.2 on 2023-06-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0011_alter_statusupload_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupload',
            name='score',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
