# Generated by Django 4.2.2 on 2023-06-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0013_alter_statusupload_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupload',
            name='note',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
