# Generated by Django 4.1.7 on 2023-07-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0015_followrequestnotifs_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupload',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
