# Generated by Django 4.1.7 on 2023-07-02 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bibilocheck', '0016_alter_statusupload_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifstatement', models.CharField(blank=True, max_length=1000, null=True)),
                ('notifby', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
