# Generated by Django 4.1.7 on 2023-07-06 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bibilocheck', '0017_notifs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupload',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('profileimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('Banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('selfdescription', models.TextField(blank=True, max_length=10000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
