# Generated by Django 4.1.7 on 2023-07-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0018_alter_statusupload_score_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='Banner',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
