# Generated by Django 4.1.7 on 2023-07-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0020_alter_bio_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
