# Generated by Django 4.1.7 on 2023-07-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0021_alter_bio_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='Banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
