# Generated by Django 4.1.7 on 2023-07-12 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bibilocheck', '0023_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalPOST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=1000000)),
                ('posttype', models.CharField(choices=[('Novel', 'Novel'), ('Fanfic', 'Fanfic'), ('Short-story', 'Short-story'), ('Poem', 'Poem'), ('other', 'other')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forumdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postdate', models.DateField(blank=True, null=True)),
                ('profilephoto', models.ImageField(upload_to='')),
                ('post', models.TextField(max_length=1000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
