# Generated by Django 4.1.7 on 2023-07-13 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0024_originalpost_forumdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumdata',
            name='postdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
