# Generated by Django 4.1.7 on 2023-07-15 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0025_alter_forumdata_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumdata',
            name='posttitle',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='forumdata',
            name='post',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='forumdata',
            name='postdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='forumdata',
            name='profilephoto',
            field=models.ImageField(blank=True, default='Bibilocheck\\static\\images\\usericon.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='originalpost',
            name='post',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
    ]
