# Generated by Django 4.2.1 on 2023-08-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0026_forumdata_posttitle_alter_forumdata_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalpost',
            name='Bookcover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='originalpost',
            name='Synopsis',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='originalpost',
            name='post',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
