# Generated by Django 4.2.1 on 2023-08-22 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0027_originalpost_bookcover_originalpost_synopsis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalpost',
            name='authorname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='originalpost',
            name='upload_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
