# Generated by Django 4.2.1 on 2023-08-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0028_originalpost_authorname_originalpost_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalpost',
            name='Booktitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
