# Generated by Django 4.2.1 on 2023-08-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0029_originalpost_booktitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalpost',
            name='UpforReview',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'NO')], max_length=255, null=True),
        ),
    ]
