# Generated by Django 4.2.1 on 2023-08-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibilocheck', '0030_originalpost_upforreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalpost',
            name='UpforReview',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=255, null=True),
        ),
    ]
